###
GET http://147.139.173.249:3004/api/activity-template/
Authorization: Bearer eeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoicml6d2FyIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzAxMDc2MTYxLCJleHAiOjE3MDExNjI1NjF9.RnVyVuJEUCu3rzjU8qhW5gTqoFXSG314uA4Tcmhn-mw